name: Atlas
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - 'migrations/*'
# Permissions to write comments on the pull request.
permissions:
  contents: read
  pull-requests: write
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ariga/atlas-action@v0
        with:
          dir: 'migrations'
          dev-url: "sqlite://file?mode=memory"
          cloud-token: ${{ secrets.ATLAS_CLOUD_TOKEN_utTMdP }}
  sync:
    needs: lint
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ariga/atlas-sync-action@v0
        with:
          dir: 'migrations'
          driver: mysql
          dev-url: sqlite://file?mode=memory
          cloud-token: ${{ secrets.ATLAS_CLOUD_TOKEN_utTMdP }}
